pmattam/Impactful

- index.html
- styles/styles.css
> change css for header and introduction image

- index.html
- scripts/main.js
- styles/styles.css
> Added Basic Location Feature

- index.html
- scripts/main.js
- styles/styles.css
> move intro image to background in css

- index.html
- styles/styles.css
> Location & Search Input Buttons

- scripts/main.js
- styles/styles.css
> Added some styling to footer and fixed map issues

- index.html
- styles/styles.css
> Updating Drop Down Menu

- .gitignore
- html/donate.html
- scripts/donate.js
- styles/donateStyles.css
- styles/styles.css
> Donate Now changes

- html/blog.html
- html/donate.html
- index.html
- scripts/main.js
- styles.css
> drop-down-menu-navigator

- html/donate.html
- styles/donateStyles.css
- styles/styles.css
@aparker22 @pmattam 
https://trello.com/c/bGmzuUHo/41-users-can-view-donate-form
> donate page css change

- html/about.html
- html/blog.html
- html/donate.html
- html/search.html
- scripts/blog.js
- styles/blogStyles.css
can search results from (News API)and display those search results on the blog page.
@jaeheekim051510 @pmattam
> Added API information for news articles relating to charities. 

- index.html
- scripts/main.js
- scripts/mapDisplay.js
- scripts/search.js
> Showing place markers for local charities on the map - https://trello.com/c/SunDykqw

- scripts/blog.js
- styles/blogStyles.css
Users can view images and click link on relevant blog articles.
> Added images and src to Blog

- html/log-in.html
- index.html
- scripts/header.js
- scripts/log-in.js
- styles/log-in.css
- styles/styles.css
@aparker22 @pmattam 
Google sign in added.
> Google Sign in added and code refactored accordingly

- html/about.html
- html/blog.html
- html/donate.html
- html/log-in.html
- html/search.html
- index.html
- styles/styles.css
Menu for desktop version is small and needs to be 100%
@jaeheekim051510 @pmattam
> Added Media Queries for Mobile and Desktop versions, 

- index.html
- styles/styles.css
> Updated media query with working map, hover, and styling changes

- html/donate.html
- html/log-in.html
- styles/donateStyles.css
- styles/log-in.css
- styles/styles.css
@aparker22  @pmattam 
I added a logo in log-in page.
> Logo in log in page

- html/search.html
- scripts/mapDisplay.js
- scripts/search.js
- styles/styles.css
…esults
@aparker22 @jaeheekim051510
> Adding map and place markers on the search page based on the search results

- html/search.html
- styles/styles.css
> Styling changes to search page

- html/donate.html
- scripts/donate.js
> Adding Donate form data to the database using firebase

- index.html
- scripts/header.js
- scripts/main.js
- styles/styles.css
@aparker22 @pmattam please check my code!
> phone view menu edited to have full screen drop down nav

- index.html
- styles/styles.css
@aparker22 @pmattam 
Please review my code.
> desktop menu nav applied
